;;; Linux compatibility layer for the shared config split.

(setq bd/default-font "Monaco for Powerline"
      bd/default-font-size 13
      bd/dired-listing-switches "-lav -G --group-directories-first --time-style=long-iso"
      bd/browser-command "qutebrowser"
      bd/dired-guess-shell-alist-user
      '(("ADF$" "geeqie")
	("CR2$" "geeqie")
	("avi$" "vlc")
	("doc$" "libreoffice")
	("docx$" "libreoffice")
	("flv$" "mplayer")
	("jpeg$" "geeqie")
	("jpg$" "geeqie")
	("m4v$" "vlc")
	("mkv$" "vlc")
	("mov$" "vlc")
	("mp3$" "mpv")
	("mp4$" "vlc")
	("mpeg$" "vlc")
	("mpg$" "vlc")
	("mts$" "vlc")
	("odp$" "libreoffice")
	("ods$" "libreoffice")
	("odt$" "libreoffice")
	("ogm$" "vlc")
	("otf$" "display")
	("pdf$" "mupdf")
	("png$" "geeqie")
	("pps$" "libreoffice")
	("ppt$" "libreoffice")
	("pptm$" "libreoffice")
	("pptx$" "libreoffice")
	("rtf$" "libreoffice")
	("svg$" "geeqie")
	("ts$" "vlc")
	("ttf$" "display")
	("webm$" "vlc")
	("webp$" "geeqie")
	("wmv$" "vlc")
	("xls$" "libreoffice")
	("xlsx$" "libreoffice")))
